spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL
    username: admin
    password: klk011101
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true
